package sfca.rulesets.appexchange_apex;

public class AvoidSecurityEnforcedOldApiVersion {
        /*
         NOTE: A TEST BASED ON SimpleAggregatorTst CAN'T WORK DUE TO THE WAY THE RULE IS WRITTEN SINCE IT DEPENDS ON THE
         API VERSION OF THE FILES IN A SALESFORCE PROJECT. THIS RULE REALLY ISN'T ONE THAT SHOULD BE WRITTEN AS A PMD RULE IN
         MY OPINION SINCE WHILE PROCESSING A *.meta.xml FILE IT ATTEMPTS TO ALSO LOOK AT AND PROCESS
         *.class FILES AS WELL, WHICH THIS TYPE OF TESTING FRAMEWORK CAN'T HANDLE.
         SO THE SECURITY TEAM WILL HAVE TO WRITE A CUSTOM TEST FOR THIS IF WE WANT COVERAGE FOR THIS RULE.
         */
}
