name: validate-pr
on:
  pull_request:
    types: [edited, opened, reopened, synchronize]

jobs:
  validate_pr_title:
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR Title
        if: github.base_ref == 'dev'
        run: |
          title="${{ github.event.pull_request.title }}"
          if [[ "$title" =~ ^(FIX|CHANGE|NEW)([[:space:]]*\([^()]+\))?[[:space:]]*:?[[:space:]]*@W-[[:digit:]]{8,9}@[[:space:]]*[:-]+.+ ]]; then
              echo "Valid PR title: '$title'"
          else
              echo "::error::Invalid PR title: '$title'. Please following the format: FIX|CHANGE|NEW (__) @W-XXXXXXXX@ Summary"
              exit 1
          fi